version: '3.4'

services:
  zookeeper:
    image: bitnami/zookeeper

  kafka:
    image: bitnami/kafka
    
  mongo-container:
    image: mongo:latest

  postgres-container:
    image: postgres:latest   
 

  sql-container:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  
  pgadmin:
    image: dpage/pgadmin4
    
#  post.query.api:
#    image: ${DOCKER_REGISTRY-}postqueryapi
#    build:
#      context: .
#      dockerfile: SM.Post/Post.Query/Post.Query.Api/Dockerfile
#
#  post.command.api:
#    image: ${DOCKER_REGISTRY-}postcommandapi
#    build:
#      context: .
#      dockerfile: SM.Post/Post.Command/Post.Command.Api/Dockerfile


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
  posgresql_data:
  pgadmin_data:

networks:
  cqrssocialmedianetwork:
    external: true